-- No data statements run while row security is disabled.
DROP POLICY sessions_update ON sessions;
DROP POLICY sessions_insert ON sessions;
DROP POLICY sessions_select ON sessions;
DROP POLICY users_delete ON users;
DROP POLICY users_insert ON users;
DROP POLICY users_select ON users;
DROP POLICY actors_update ON actors;
DROP POLICY actors_insert ON actors;
DROP POLICY actors_select ON actors;
DROP POLICY channel_members_delete ON channel_members;
DROP POLICY channel_members_insert ON channel_members;
DROP POLICY channel_members_select ON channel_members;
DROP POLICY audit_events_insert ON audit_events;
DROP POLICY invites_update ON invites;
DROP POLICY invites_insert ON invites;
DROP POLICY invites_select ON invites;
DROP POLICY team_members_delete ON team_members;
DROP POLICY team_members_update ON team_members;
DROP POLICY team_members_insert ON team_members;
DROP POLICY team_members_select ON team_members;
DROP POLICY messages_insert ON messages;
DROP POLICY messages_select ON messages;
DROP POLICY channels_update ON channels;
DROP POLICY channels_insert ON channels;
DROP POLICY channels_select ON channels;
DROP POLICY teams_insert ON teams;
DROP POLICY teams_select ON teams;
DROP POLICY organization_members_update ON organization_members;
DROP POLICY organization_members_insert ON organization_members;
DROP POLICY organization_members_select ON organization_members;
DROP POLICY organizations_update ON organizations;
DROP POLICY organizations_insert ON organizations;
DROP POLICY organizations_select ON organizations;
DROP POLICY organization_members_select_owner ON organization_members;
ALTER TABLE organizations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE organization_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE organization_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE teams NO FORCE ROW LEVEL SECURITY;
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE channels NO FORCE ROW LEVEL SECURITY;
ALTER TABLE channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE channel_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE channel_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE invites NO FORCE ROW LEVEL SECURITY;
ALTER TABLE invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE actors NO FORCE ROW LEVEL SECURITY;
ALTER TABLE actors DISABLE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
DROP FUNCTION fukulow_active_organizations();
DROP FUNCTION fukulow_organization_has_members(uuid);
DROP TRIGGER organization_members_guard_inactive_role ON organization_members;
DROP FUNCTION fukulow_guard_inactive_member_role();
DROP INDEX organization_members_actor_id_idx;
DROP INDEX team_members_actor_id_idx;
